const fs = require('fs');
const path = require('path');
const http = require('http');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fixed = true;
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'ui-test-results', Date.now().toString()); fs.mkdirSync(out, { recursive:true });
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
function mock(){
 const long='Muhammad Abdurrahman Pratama';
 const members=Array.from({length:8},(_,i)=>({id:`member-${i}`,name:i?long+' '+(i+1):'Pengelola Kelas',username:'1234567890123456789012345678901234567890',number:i+1,role:i?'student':'developer',class_role:'Anggota',quote:'Bersama belajar dan berkembang. '.repeat(12)}));
 const tasks=[{id:'task-1',title:'Konfigurasi jaringan dan dokumentasi topologi laboratorium',subject:'Administrasi Infrastruktur Jaringan',due:'2026-09-07',description:'Dokumentasi_jaringan_laboratorium_'.repeat(5),teacher:long}];
 const tables={members,tasks,task_summaries:tasks,task_progress:[],class_profile:[],schedules:[{day:'monday',lessons:[{time:'07.00–08.30',subject:'Administrasi Infrastruktur Jaringan',teacher:long,room:'Laboratorium TKJ'}],piket:members.map(m=>m.name)}],apel_queue:members.map((m,i)=>({id:m.id,name:m.name,position:i})),resources:[{id:'resource-1',name:'Dokumentasi_Konfigurasi_Jaringan_Laboratorium_'.repeat(4)+'.pdf',subject:'Administrasi Infrastruktur Jaringan',kind:'materi',size:100000,drive_file_id:'test-file'}]};
 const user={id:'member-0',user_metadata:{name:'Pengelola Kelas'}};
 window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:location.pathname.includes('/login')?null:{user,access_token:'local-test'}}}),signOut:async()=>({}),signInWithPassword:async()=>({error:{message:'Simulasi lokal: kredensial tidak dikirim.'}})},from(table){let single=false;const q={select(){return q},eq(){return q},order(){return q},maybeSingle(){single=true;return q},then(resolve,reject){return Promise.resolve({data:single?(tables[table]?.[0]||null):(tables[table]||[]),error:null}).then(resolve,reject)}};return q},channel(){return{on(){return this},subscribe(){return this}}},removeChannel(){}})};
}
async function setup(page){await page.route('**/*',route=>{const url=route.request().url();if(new URL(url).pathname==="/api/config")return route.fulfill({contentType:"application/json",body:JSON.stringify({url:"https://classroom.invalid",publishableKey:"sb_publishable_local_test_configuration"})});if(url.includes('/@supabase/supabase-js'))return route.fulfill({contentType:'text/javascript',body:`(${mock.toString()})();`});if(url.startsWith('http://127.0.0.1:'))return route.continue();if(/fonts\.(googleapis|gstatic)\.com|cdn.jsdelivr.net\/npm\/@tabler/.test(url))return route.continue();return route.abort();});}
async function overflow(page){return page.evaluate(()=>[...document.querySelectorAll('main *,.login-page *')].filter(el=>{const s=getComputedStyle(el),r=el.getBoundingClientRect();if(!r.width||s.visibility==='hidden'||el.closest('.schedule-panel,.admin-nav'))return false;return r.right>innerWidth+2||r.left< -2||((el.matches('h1,h2,h3,strong,p,.result-cell,.task-card,.resource-row'))&&el.scrollWidth>el.clientWidth+3)}).map(el=>({tag:el.tagName,cls:el.className,text:el.textContent.slice(0,70),width:el.clientWidth,scroll:el.scrollWidth,right:Math.round(el.getBoundingClientRect().right)})));}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({...(process.env.UI_BROWSER_PATH ? {executablePath:process.env.UI_BROWSER_PATH} : process.platform === 'win32' ? {channel:'msedge'} : {}),headless:true});
const report=[];
for(const width of [320,390,768,1024,1440]){const page=await browser.newPage({viewport:{width,height:900}});await setup(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const route of ['/','/jadwal/','/tugas/','/tools/','/penyimpanan/','/anggota/','/profile/','/admin/','/login/','/admin/login/']){await page.goto(base+route,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(300);report.push({width,route,overflow:await overflow(page),errors:errors.splice(0)});if([390,1440].includes(width)&&['/','/tools/','/anggota/'].includes(route))await page.screenshot({path:path.join(out,`${width}-${route.replaceAll('/','')||'home'}.png`),fullPage:true,animations:'disabled'});if(route==='/admin/')for(const tab of ['schedule','apel','tasks','users']){await page.locator(`[data-admin-tab="${tab}"]`).click();report.push({width,route:'/admin/#'+tab,overflow:await overflow(page),errors:errors.splice(0)});}}
await page.goto(base+'/');if(width>820){await page.locator('.sidebar-collapse').click();await page.waitForTimeout(300);await page.screenshot({path:path.join(out,`${width}-collapsed.png`)});const avatar=await page.locator('.profile-avatar').boundingBox();report.push({width,route:'collapsed',avatar});}await page.close();}
fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.filter(x=>x.overflow?.length||x.errors?.length||x.avatar),null,2));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});


