const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'ui-test-results','loading-'+Date.now());fs.mkdirSync(out,{recursive:true});
const fixture=fs.readFileSync(path.join(__dirname,'ui-access.cjs'),'utf8');
const mock=fixture.slice(fixture.indexOf('function mock(){'),fixture.indexOf('\n(async()=>'))
 .replace('window.__reads.push(table);','window.__reads.push(table); if (!single && window.__options.readDelay?.[table]) await new Promise(r=>setTimeout(r,window.__options.readDelay[table]));')
 .replace('rpc:async(name,{entries})=>{','rpc:async(name,{entries})=>{ if(window.__writeDelay)await new Promise(r=>setTimeout(r,window.__writeDelay));')
 .replace('updateUser:async()=>({error:null})','updateUser:async()=>{window.__passwordWrites=(window.__passwordWrites||0)+1;await new Promise(r=>setTimeout(r,window.__writeDelay||0));return {error:window.__writeFail?{message:"Gagal menyimpan"}:null}}');
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'msedge',headless:true});const results=[];
try {
async function create(route,options={}){const p=await browser.newPage({viewport:{width:options.width||1440,height:900}});p.setDefaultTimeout(10000);p.errors=[];p.on('pageerror',e=>p.errors.push(e.message));await p.addInitScript(options=>{window.__options={role:'developer',...options};if(options.dark)localStorage.setItem('clouven-theme','dark')},options);await p.route('**/*',async r=>{let url=r.request().url();if(new URL(url).pathname==='/api/config')return r.fulfill({contentType:'application/json',body:JSON.stringify({url:'https://test.invalid',publishableKey:'sb_publishable_isolated_test'})});if(url.includes('/@supabase/supabase-js'))return r.fulfill({contentType:'text/javascript',body:mock+'mock();'});if(url.startsWith(base+'/api/')){await p.evaluate(()=>window.__api.push({pending:true}));await new Promise(r=>setTimeout(r,1100));return r.fulfill({status:503,contentType:'application/json',body:'{"error":"Gagal menyimpan. Coba lagi."}'})}if(url.startsWith(base))return r.continue();return r.abort()});await p.goto(base+route);return p}
async function check(name,fn){if(process.env.UI_TEST_FILTER && !new RegExp(process.env.UI_TEST_FILTER).test(name))return;await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}
async function finish(p){assert.deepEqual(p.errors,[]);await p.close()}
async function stable(before,button){const after=await button.boundingBox();for(const k of ['x','y','width','height'])assert.ok(Math.abs(before[k]-after[k])<1.1,`${k}: ${before[k]} -> ${after[k]}`)}
for(const width of [390,1440])for(const dark of [false,true])for(const [route,table,host] of [['/anggota/','members','#memberGrid'],['/tugas/','tasks','#tasksGrid']])await check(`${route} ${width}px ${dark?'dark':'light'} card-shaped shimmer and reduced motion`,async()=>{const p=await create(route,{width,dark,readDelay:{[table]:2200}});await p.locator(host+' .loading-card').first().waitFor();assert.equal(await p.locator(host).getAttribute('aria-busy'),'true');assert.equal(await p.locator(host+' button').count(),0);assert.equal(await p.locator(host+' .loading-card').count(),table==='members'?8:6);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const shape=p.locator(host+' .loading-shape').first();assert.equal(await shape.evaluate(e=>getComputedStyle(e,'::after').animationName),'card-loading-shimmer');await p.waitForTimeout(450);await p.screenshot({path:path.join(out,`${table}-${width}-${dark?'dark':'light'}.png`),fullPage:true});await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await shape.evaluate(e=>getComputedStyle(e,'::after').animationName),'none');await p.locator(host+' .loading-card').first().waitFor({state:'detached'});assert.equal(await p.locator(host).getAttribute('aria-busy'),'false');await finish(p)});
await check('Instagram dialog keeps button bounds, blocks duplicates, preserves values after failure',async()=>{const p=await create('/profile/');await p.locator('#editMyInstagram').click();const form=p.locator('.action-modal form'),button=form.locator('[type=submit]');await form.locator('[name=instagram]').fill('javiersatya_');const before=await button.boundingBox();await button.click();await p.locator('.is-button-loading').waitFor();await stable(before,button);assert.equal(await button.getAttribute('aria-busy'),'true');assert.equal(await button.isDisabled(),true);await p.evaluate(()=>document.querySelector('.action-modal form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await p.screenshot({path:path.join(out,'instagram-saving.png'),fullPage:true});await form.locator('[data-error]').waitFor();assert.equal(await p.evaluate(()=>window.__api.length),1);assert.equal(await button.isEnabled(),true);assert.equal(await button.getAttribute('aria-busy'),null);assert.equal(await button.innerText(),'Simpan perubahan');assert.equal(await form.locator('[name=instagram]').inputValue(),'javiersatya_');await finish(p)});
for(const tab of ['profile','schedule','tasks'])await check(`Admin ${tab} save has stable button and recovers after failure`,async()=>{const p=await create('/admin/');await p.locator('#profileForm').waitFor();if(tab!=='profile')await p.locator(`[data-admin-tab="${tab}"]`).click();const id={profile:'profileForm',schedule:'scheduleForm',tasks:'taskForm'}[tab],form=p.locator('#'+id);await form.waitFor();if(tab==='tasks'){await form.locator('[name=title]').fill('Tugas pengujian');await form.locator('[name=subject]').selectOption('ASJ',{force:true});await form.locator('[name=due]').fill('2026-10-10')}await p.evaluate(()=>{window.__writeDelay=1100;window.__writeFail=true});const button=form.locator('[type=submit]');await button.scrollIntoViewIfNeeded();const before=await button.boundingBox();await button.click();await button.locator('.button-loading-spinner').waitFor();await stable(before,button);await p.evaluate(id=>document.querySelector('#'+id).dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})),id);await button.locator('.button-loading-spinner').waitFor({state:'detached'});assert.equal(await button.isEnabled(),true);assert.equal(await p.evaluate(()=>window.__writes.length),1);await finish(p)});
await check('Password save cannot submit twice and resets loading after rejection',async()=>{const p=await create('/profile/');const form=p.locator('#passwordForm');await form.locator('[name=password]').fill('sample-pass-123');await p.evaluate(()=>{window.__writeDelay=900;window.__writeFail=true});const button=form.locator('button[type=submit], button:not([type])');await button.click();await button.locator('.button-loading-spinner').waitFor();await p.evaluate(()=>document.querySelector('#passwordForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await button.locator('.button-loading-spinner').waitFor({state:'detached'});assert.equal(await p.evaluate(()=>window.__passwordWrites),1);assert.equal(await form.locator('[name=password]').inputValue(),'sample-pass-123');await finish(p)});
await check('Shared button restores original icon nodes, styles and accessible name',async()=>{const p=await create('/profile/');await p.locator('#editMyInstagram').waitFor();const result=await p.evaluate(async()=>{const {startButtonLoading}=await import('/assets/js/loading-ui.js');const b=document.querySelector('#editMyInstagram'),nodes=[...b.childNodes],before=b.getBoundingClientRect();const loading=startButtonLoading(b);const during=b.getBoundingClientRect();loading.finish();return {same:nodes.every((n,i)=>n===b.childNodes[i]),width:Math.abs(before.width-during.width),height:Math.abs(before.height-during.height),busy:b.getAttribute('aria-busy'),disabled:b.disabled}});assert.ok(result.same);assert.ok(result.width<1&&result.height<1);assert.equal(result.busy,null);assert.equal(result.disabled,false);await finish(p)});

for (const [route,table,host] of [['/anggota/','members','#memberGrid'],['/tugas/','tasks','#tasksGrid']]) await check(route+' background refresh keeps existing cards visible',async()=>{
 const p=await create(route);await p.locator(host+' [data-member], '+host+' [data-toggle]').first().waitFor();
 await p.evaluate(({table,host})=>{window.__firstCard=document.querySelector(host).firstElementChild;window.__options.readDelay={[table]:1200};window.__channels.filter(c=>c.table===table).forEach(c=>c.callback())},{table,host});
 assert.equal(await p.locator(host+' .loading-card').count(),0);assert.equal(await p.locator(host).getAttribute('aria-busy'),'false');
 assert.equal(await p.evaluate(host=>document.querySelector(host).firstElementChild===window.__firstCard,host),true);await finish(p);
});
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('Report: '+out);
} finally {await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
