-- Apply after all earlier ClouvenTwo migrations. Reminders are generated by a trusted scheduler.
begin;

alter table public.tasks add column if not exists due_at timestamptz;
alter table public.task_summaries add column if not exists due_at timestamptz;
alter table public.tasks add constraint tasks_due_at_requires_date check (due_at is null or due is not null);
create index if not exists tasks_due_at_idx on public.tasks(due_at) where due_at is not null;
create or replace function public.sync_task_summary()
returns trigger language plpgsql security definer set search_path='' as $$
begin
 if tg_op='DELETE' then delete from public.task_summaries where id=old.id; return old; end if;
 insert into public.task_summaries(id,title,subject,due,due_at,status,updated_at)
 values(new.id,new.title,new.subject,new.due,new.due_at,new.status,new.updated_at)
 on conflict(id) do update set title=excluded.title,subject=excluded.subject,due=excluded.due,
 due_at=excluded.due_at,status=excluded.status,updated_at=excluded.updated_at;
 return new;
end; $$;
update public.task_summaries s set due_at=t.due_at from public.tasks t where s.id=t.id;

create table public.calendar_events (
 id uuid primary key default gen_random_uuid(),
 title text not null check (char_length(btrim(title)) between 1 and 160),
 description text not null default '' check (char_length(description) <= 4000),
 event_type text not null default 'event' check (event_type in ('exam','event','holiday','meeting','practice','other')),
 start_at timestamptz not null,
 end_at timestamptz not null,
 all_day boolean not null default false,
 location text not null default '' check (char_length(location) <= 160),
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 notification_enabled boolean not null default false,
 notification_offset integer not null default 60 check (notification_offset in (0,10,30,60,1440)),
 constraint calendar_event_range check (end_at > start_at)
);
create index calendar_events_start_idx on public.calendar_events(start_at);
alter table public.calendar_events enable row level security;
grant select on public.calendar_events to authenticated;
grant insert(title,description,event_type,start_at,end_at,all_day,location,created_by,notification_enabled,notification_offset) on public.calendar_events to authenticated;
grant update(title,description,event_type,start_at,end_at,all_day,location,notification_enabled,notification_offset) on public.calendar_events to authenticated;
grant delete on public.calendar_events to authenticated;
grant all on public.calendar_events to service_role;
create policy "Members read calendar" on public.calendar_events for select to authenticated using (public.has_app_role('student'));
create policy "Managers create calendar" on public.calendar_events for insert to authenticated with check (public.has_app_role('class_officer') and created_by = (select auth.uid()));
create policy "Managers update calendar" on public.calendar_events for update to authenticated using (public.has_app_role('class_officer')) with check (public.has_app_role('class_officer'));
create policy "Managers delete calendar" on public.calendar_events for delete to authenticated using (public.has_app_role('class_officer'));
create or replace function public.touch_calendar_event() returns trigger language plpgsql set search_path='' as $$
begin new.updated_at=now(); return new; end; $$;
revoke all on function public.touch_calendar_event() from public,anon,authenticated;
create trigger touch_calendar_event before update on public.calendar_events for each row execute function public.touch_calendar_event();

create table public.notification_preferences (
 user_id uuid primary key references auth.users(id) on delete cascade,
 assignment_reminders boolean not null default true,
 calendar_reminders boolean not null default true,
 updated_at timestamptz not null default now()
);
alter table public.notification_preferences enable row level security;
grant select, insert on public.notification_preferences to authenticated;
grant update(assignment_reminders,calendar_reminders) on public.notification_preferences to authenticated;
grant all on public.notification_preferences to service_role;
create policy "Read own notification preferences" on public.notification_preferences for select to authenticated using (user_id = (select auth.uid()) and public.has_app_role('student'));
create policy "Create own notification preferences" on public.notification_preferences for insert to authenticated with check (user_id = (select auth.uid()) and public.has_app_role('student'));
create policy "Update own notification preferences" on public.notification_preferences for update to authenticated using (user_id = (select auth.uid()) and public.has_app_role('student')) with check (user_id = (select auth.uid()) and public.has_app_role('student'));
create or replace function public.touch_notification_preferences() returns trigger language plpgsql set search_path='' as $$
begin new.updated_at=now(); return new; end; $$;
revoke all on function public.touch_notification_preferences() from public,anon,authenticated;
create trigger touch_notification_preferences before update on public.notification_preferences for each row execute function public.touch_notification_preferences();

create table public.notifications (
 id uuid primary key default gen_random_uuid(),
 user_id uuid not null references auth.users(id) on delete cascade,
 type text not null check (type in ('assignment_new','assignment_due','calendar_new','calendar_reminder','schedule_change')),
 title text not null check (char_length(title) between 1 and 180),
 message text not null default '' check (char_length(message) <= 600),
 related_id text,
 target_url text not null check (target_url ~ '^/(tugas|kalender|jadwal)/'),
 dedupe_key text not null,
 created_at timestamptz not null default now(),
 read_at timestamptz,
 unique(user_id,dedupe_key)
);
create index notifications_user_latest_idx on public.notifications(user_id,created_at desc);
create index notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;
alter table public.notifications enable row level security;
grant select on public.notifications to authenticated;
grant update(read_at) on public.notifications to authenticated;
grant all on public.notifications to service_role;
create policy "Read own notifications" on public.notifications for select to authenticated using (user_id = (select auth.uid()) and public.has_app_role('student'));
create policy "Mark own notifications read" on public.notifications for update to authenticated using (user_id = (select auth.uid()) and public.has_app_role('student')) with check (user_id = (select auth.uid()) and public.has_app_role('student'));

create or replace function public.productivity_broadcast() returns trigger language plpgsql security definer set search_path = '' as $$
begin
 if tg_table_name = 'tasks' then
  if tg_op = 'INSERT' then
   insert into public.notifications(user_id,type,title,message,related_id,target_url,dedupe_key)
   select m.id,'assignment_new','Tugas baru: '||left(new.title,140),left(new.subject,600),new.id,'/tugas/?task='||new.id,'task:new:'||new.id
   from public.members m where m.role in ('student','class_officer','teacher','developer') on conflict do nothing;
  end if;
 elsif tg_table_name = 'calendar_events' then
  if tg_op = 'INSERT' then
   insert into public.notifications(user_id,type,title,message,related_id,target_url,dedupe_key)
   select m.id,'calendar_new','Kegiatan baru: '||left(new.title,140),left(new.location,600),new.id::text,'/kalender/?event='||new.id,'event:new:'||new.id
   from public.members m where m.role in ('student','class_officer','teacher','developer') on conflict do nothing;
  end if;
 elsif tg_table_name = 'schedules' and new.lessons is distinct from old.lessons then
  insert into public.notifications(user_id,type,title,message,related_id,target_url,dedupe_key)
   select m.id,'schedule_change','Jadwal pelajaran berubah','Jadwal '||case new.day when 'monday' then 'Senin' when 'tuesday' then 'Selasa' when 'wednesday' then 'Rabu' when 'thursday' then 'Kamis' else 'Jumat' end||' telah diperbarui.',new.day,'/jadwal/','schedule:'||new.day||':'||to_char(now() at time zone 'Asia/Jakarta','YYYY-MM-DD')
  from public.members m where m.role in ('student','class_officer','teacher','developer') on conflict do nothing;
 end if;
 return new;
end; $$;
revoke all on function public.productivity_broadcast() from public,anon,authenticated;
create trigger productivity_task_new after insert on public.tasks for each row execute function public.productivity_broadcast();
create trigger productivity_event_new after insert on public.calendar_events for each row execute function public.productivity_broadcast();
create trigger productivity_schedule_changed after update on public.schedules for each row execute function public.productivity_broadcast();

create or replace function public.generate_productivity_reminders() returns integer language plpgsql security definer set search_path = '' as $$
declare added integer := 0; n integer; now_jakarta timestamp := now() at time zone 'Asia/Jakarta';
begin
 -- The unique (user_id,dedupe_key) constraint makes retries harmless. Date-only tasks end at 23:59 Jakarta time.
 with due_tasks as (
  select t.*, coalesce(t.due_at,((t.due + time '23:59:59') at time zone 'Asia/Jakarta')) as deadline
  from public.tasks t where t.status='open' and t.due is not null and t.due between now_jakarta::date and now_jakarta::date + 2
 ), thresholds as (select * from (values (1440,'1 hari'),(180,'3 jam'),(30,'30 menit')) v(minutes,label))
 insert into public.notifications(user_id,type,title,message,related_id,target_url,dedupe_key)
 select m.id,'assignment_due','Deadline tugas: '||left(t.title,140),'Tenggat '||h.label||' lagi.',t.id,'/tugas/?task='||t.id,
        'task:due:'||t.id||':'||t.deadline||':'||h.minutes
 from due_tasks t cross join thresholds h join public.members m on m.role in ('student','class_officer','teacher','developer')
 left join public.task_progress p on p.task_id=t.id and p.user_id=m.id
 left join public.notification_preferences pref on pref.user_id=m.id
 where coalesce(pref.assignment_reminders,true) and not coalesce(p.done,false)
   and t.deadline > now() and t.deadline - make_interval(mins=>h.minutes) <= now()
   and t.deadline - make_interval(mins=>h.minutes) > now() - interval '20 minutes'
 on conflict do nothing;
 get diagnostics n = row_count; added := added+n;
 insert into public.notifications(user_id,type,title,message,related_id,target_url,dedupe_key)
 select m.id,'calendar_reminder','Pengingat: '||left(e.title,140),'Kegiatan segera dimulai.',e.id::text,'/kalender/?event='||e.id,
        'event:reminder:'||e.id||':'||e.start_at||':'||e.notification_offset
 from public.calendar_events e join public.members m on m.role in ('student','class_officer','teacher','developer')
 left join public.notification_preferences pref on pref.user_id=m.id
 where e.notification_enabled and coalesce(pref.calendar_reminders,true)
   and e.start_at < now() + interval '1 day'
   and e.start_at > now() - interval '20 minutes' and e.start_at - make_interval(mins=>e.notification_offset) <= now()
   and e.start_at - make_interval(mins=>e.notification_offset) > now() - interval '20 minutes'
 on conflict do nothing;
 get diagnostics n = row_count; return added+n;
end; $$;
revoke all on function public.generate_productivity_reminders() from public,anon,authenticated;
grant execute on function public.generate_productivity_reminders() to service_role;
do $$ begin
 if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then
  alter publication supabase_realtime add table public.notifications;
 end if;
 if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='calendar_events') then
  alter publication supabase_realtime add table public.calendar_events;
 end if;
end $$;
commit;
